-- Nova auth schema — run in your Oracle Workspace (SQL Workshop → SQL Commands).
-- Stores app users for login/register + Google sign-in.

CREATE TABLE nova_users (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  email         VARCHAR2(255) NOT NULL,
  name          VARCHAR2(200),
  password_hash VARCHAR2(255),                 -- NULL for Google-only accounts
  provider      VARCHAR2(20)  DEFAULT 'local', -- local | google
  created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT nova_users_email_uq UNIQUE (email)
);
